version: '1.0'
name: master-pipeline
displayName: MasterPipeline
triggers:
  trigger: auto
  push:
    branches:
      include:
        - master
    paths:
      precise:
        - package.json
stages:
  - name: compile
    displayName: 编译并上传
    strategy: naturally
    trigger: auto
    steps:
      - step: build@nodejs
        name: build_nodejs
        displayName: Nodejs 构建
        nodeVersion: 18.16.0
        commands:
          - rm -rf ./dist
          - yum install wine.el7
          - yarn
          - yarn build -m electron -T win -A x64
        caches:
          - ./node_modules
          - ~/.cache
        strategy:
          retry: '1'
