version: '1.0'
name: master-pipeline
displayName: MasterPipeline
triggers:
  trigger: auto
  push:
    branches:
      include:
        - master
    paths:
      precise:
        - package.json
variables:
  global:
    - RSYNC_PASSWORD
stages:
  - name: compile
    displayName: 编译并上传
    strategy: naturally
    trigger: auto
    steps:
      - step: build@nodejs
        name: build_nodejs
        displayName: Nodejs 构建
        nodeVersion: 18.16.0
        commands:
          - set -e
          - yum install --repo baseos -y rsync
          - mkdir -p ~/.cache/gost
          - curl -so gost_lastest_release https://api.github.com/repos/ginuerzh/gost/releases/latest
          - gost_version=$(cat gost_lastest_release | grep tag_name | grep -o '[v0-9.]*')
          - if [ ! -f ~/.cache/gost_version ] || [ $(cat ~/.cache/gost_version) != $gost_version ]; then
          - curl -so ~/.cache/gost.tar.gz "https://ghp.ci/$(cat gost_lastest_release | grep -o 'https://.*_linux_amd64\.tar\.gz')"
          - tar -zxf ~/.cache/gost.tar.gz -C ~/.cache/gost
          - rm -f ~/.cache/gost.tar.gz
          - echo $gost_version > ~/.cache/gost_version
          - fi
          - rm -f gost_lastest_release
          - export RSYNC_PASSWORD='${RSYNC_PASSWORD}'
          - ~/.cache/gost/gost -L=:8080 -F=kcp://sdmht:$RSYNC_PASSWORD@sdmht.star2000.work:53 &
          - trap "kill -9 $!" EXIT
          - export RSYNC_PROXY=127.0.0.1:8080
          - yarn
          - yarn build -m pwa
          - rsync -chrvz --exclude service-worker.js ./dist/pwa/ sdmht@sdmht.star2000.work::sdmht
          - rsync -chrvz --delete-after ./dist/pwa/ sdmht@sdmht.star2000.work::sdmht
        caches:
          - node_modules
          - ~/.cache
        strategy:
          timeout: 20
          retry: '0'
strategy:
  cloneDepth: 1
