version: '1.0'
name: master-pipeline
displayName: MasterPipeline
triggers:
  trigger: auto
  push:
    branches:
      include:
        - master
    commitMessages:
      include:
        - '[0-9]+\.[0-9]+\.[0-9]+'
stages:
  - name: compile
    displayName: 编译
    strategy: naturally
    trigger: auto
    steps:
      - step: build@nodejs
        name: build_nodejs
        displayName: Nodejs 构建
        nodeVersion: 18.16.0
        commands:
          - npm i -g yarn
          - yarn
          - rm -rf ./dist
          - yarn build -m pwa
          - yarn build -m electron -T win -A x64
          - rm -rf ./dist/electron/Packaged/*-unpacked/
          - rm -rf ./dist/electron/Packaged/builder-*
          - rm -rf ./dist/electron/UnPackaged/
        artifacts:
          - name: BUILD_ARTIFACT
            path:
              - ./dist
        caches:
          - ./node_modules
        strategy:
          retry: '1'
      - step: publish@general_artifacts
        name: publish_general_artifacts
        displayName: 上传制品
        dependArtifact: BUILD_ARTIFACT
        artifactName: output
        strategy: {}
        dependsOn: build_nodejs
  - name: release
    displayName: 发布
    strategy: naturally
    trigger: auto
    steps:
      - step: publish@release_artifacts
        name: publish_release_artifacts
        displayName: 发布
        dependArtifact: output
        version: 1.0.0.0
        autoIncrement: true
        strategy: {}
