version: '1.0'
name: master-pipeline
displayName: MasterPipeline
triggers:
  trigger: auto
  push:
    branches:
      include:
        - master
    paths:
      precise:
        - package.json
variables:
  global:
    - RSYNC_PASSWORD
stages:
  - name: compile
    displayName: 编译
    strategy: naturally
    trigger: auto
    steps:
      - step: build@nodejs
        name: build_nodejs
        displayName: Nodejs 构建
        nodeVersion: 18.16.0
        commands:
          - set -e
          - yarn
          - yarn build -m pwa
        artifacts:
          - name: BUILD_ARTIFACT
            path:
              - ./dist/pwa/
        caches:
          - node_modules
        strategy: {}
  - name: publish
    displayName: 部署
    strategy: naturally
    trigger: auto
    executor: []
    steps:
      - step: execute@docker
        name: execute_by_docker
        displayName: 基于镜像的脚本执行
        certificate: ''
        image: instrumentisto/rsync-ssh
        command:
          - export RSYNC_PASSWORD='${RSYNC_PASSWORD}'
          - rsync -chrvz --exclude service-worker.js ./target/ sdmht@sdmht.star2000.work::sdmht
          - rsync -chrvz --delete-after ./target/ sdmht@sdmht.star2000.work::sdmht
        artifacts:
          - name: BUILD_ARTIFACT
            path:
              - ./target
        notify: []
        strategy:
          retry: '0'
strategy:
  cloneDepth: 1
