version: '1.0'
name: master-pipeline
displayName: MasterPipeline
triggers:
  trigger: auto
  push:
    branches:
      include:
        - master
    paths:
      precise:
        - package.json
stages:
  - name: compile
    displayName: 编译并上传
    strategy: naturally
    trigger: auto
    steps:
      - step: build@nodejs
        name: build_nodejs
        displayName: Nodejs 构建
        nodeVersion: 18.16.0
        commands:
          - docker run --rm -ti \
          - ' --env-file < $(env) \'
          - ' --env ELECTRON_CACHE="/root/.cache/electron" \'
          - ' --env ELECTRON_BUILDER_CACHE="/root/.cache/electron-builder" \'
          - ' -v ${PWD}:/project \'
          - ' -v ~/.cache/electron:/root/.cache/electron \'
          - ' -v ~/.cache/electron-builder:/root/.cache/electron-builder \'
          - ' electronuserland/builder:wine \'
          - ' /bin/bash -c "yarn && yarn build -m electron -T win -A x64"'
        caches:
          - node_modules
          - ~/.cache/electron
          - ~/.cache/electron-builder
        strategy:
          retry: '1'
      - step: execute@docker
        name: execute_by_docker
        displayName: 基于镜像的脚本执行
        certificate: ''
        image: electronuserland/builder:wine
        command:
          - yarn && yarn build -m electron -T win -A x64
        notify: []
        strategy:
          retry: '0'
