on:
  push:
    branches:
      - main
      - dev
    paths-ignore:
      - '**.md'
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    name: 编译并部署
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - env:
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_PORT: ${{ secrets.SSH_PORT }}
          SSH_KEY: ${{ secrets.SSH_KEY }}
          DEPLOY_PATH: /srv/http/${{ github.event.repository.name }}_${{ github.ref_name }}
        run: |
          yarn
          yarn build
          sudo apt install -y rsync
          mkdir -p ~/.ssh
          echo "$SSH_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -p $SSH_PORT $SSH_HOST >> ~/.ssh/known_hosts
          rsync -e "ssh -p $SSH_PORT" -chrvz --exclude service-worker.js ./dist/pwa/ $SSH_USER@$SSH_HOST:$DEPLOY_PATH
          rsync -e "ssh -p $SSH_PORT" -chrvz --delete-after ./dist/pwa/ $SSH_USER@$SSH_HOST:$DEPLOY_PATH
